# Generated by Django 5.0.1 on 2024-02-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_otp_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp_verification',
            old_name='mobile',
            new_name='email',
        ),
    ]
