# Generated by Django 5.0.1 on 2024-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_mobile_otp_verification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_verification',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otp_verification',
            name='counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
