# Generated by Django 5.0.1 on 2024-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_otp_verification_otp_alter_otp_verification_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_verification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
