# Generated by Django 5.0.1 on 2024-02-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_otp_verification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp_verification',
            name='email',
        ),
    ]
