# Generated by Django 5.0.1 on 2024-02-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
