# Generated by Django 5.0.1 on 2024-02-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_userprofile_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
